/**
 * Autogenerated file
 * Create time 2018-12-13 12:15:13.015604 +0100 CET m=+0.015272623
 * Copyright (c) 2019 Adcubum AG
 *
 */
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {ApiService} from './apiService.js'

/**
 *  `TaskService` Collection
 */

/**
 * Interface Definitonen für das Modul Task 
Zweck diese Moduls ist es sowas wie eine TO-DO Liste zu haben
 */

/**
 * package: task
 * version: 1
 */

/**
 * @customElement
 * @polymer
 * @extends PolymerElement
 * @appliesMixin ApiService
 * @demo demo/index.html
 */
class TaskServiceList extends ApiService(PolymerElement) {

    static get properties() {
        return {
            /**
             * Collection Model
             * Type TaskCollection with TaskEntity inside
             */
            list: {
                type: Array,
            },
            /**
             * Hypermedia As The Engine Of Application State (HATEOAS)
             * Array of HATEOAS links
             * z.B. next, first, last page
             */
            hateoas: Array,
        };
    }

    
    /**
     *  ```
     *  rpc ListTask (ListTaskRequest) returns (TaskCollection) {
     *      option (google.api.http) = {
     *          get: "/tasks"
     *      };
     *  }
     *  ```
     * @public
     */
    listTask() { 
        const getRequest = new Request('/tasks', {method: 'GET', headers: {}});
        this.generateRequest(getRequest);
        
    }


    /**
     * Follows Hateoas rel=prev
     */
    prevPage() {
        const follow = 'prev';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }

    /**
     * Follows Hateoas rel=next
     */
    nextPage() {
        const follow = 'next';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }

    /**
     * Follows Hateoas rel=first
     */
    firstPage() {
        const follow = 'first';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }

    /**
     * Follows Hateoas rel=last
     */
    lastPage() {
        const follow = 'last';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }
}

window.customElements.define('task-service-list', TaskServiceList);
