/**
 * Autogenerated file
 * Create time 2018-12-21 12:27:05.951417 +0100 CET m=+0.002958098
 * Copyright (c) 2019 Adcubum AG
 *
 */
import {PolymerElement} from '@polymer/polymer/polymer-element.js';
import {ApiService} from './apiService.js'

/**
 *  `TagService` Collection
 */

/**
 * Interface Definitonen für die Entity Tags 
Verwaltet Tags
 */

/**
 * package: tags
 * version: 1
 */

/**
 * @customElement
 * @polymer
 * @extends PolymerElement
 * @appliesMixin ApiService
 * @demo demo/index.html
 */
class TagServiceList extends ApiService(PolymerElement) {

    static get properties() {
        return {
            /**
             * Collection Model
             * Array of entities
             */
            list: {
                type: Array,
            },
            /**
             * Hypermedia As The Engine Of Application State (HATEOAS)
             * Array of HATEOAS links
             * z.B. next, first, last page
             */
            hateoas: Array,
        };
    }

    
    /**
     *  ```
     *  rpc ListAllTags (ListParams) returns (TagCollectionResponse) {
     *      option (google.api.http) = {
     *          get: "/v1/tags"
     *      };
     *  }
     *  ```
     * @public
     */
    listAllTags() { 
        const getRequest = new Request('/v1/tags', {method: 'GET', headers: {}});
        this.generateRequest(getRequest);
        
    }
    /**
     *  ```
     *  rpc ListTagsFromTask (ListParams) returns (TagCollectionResponse) {
     *      option (google.api.http) = {
     *          get: "/v1/{parent=tasks/*}/tags"
     *      };
     *  }
     *  ```
     * @public
     */
    listTagsFromTask() { 
        const getRequest = new Request('/v1/{parent=tasks/*}/tags', {method: 'GET', headers: {}});
        this.generateRequest(getRequest);
        
    }


    /**
     * Follows Hateoas rel=prev
     */
    prevPage() {
        const follow = 'prev';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }

    /**
     * Follows Hateoas rel=next
     */
    nextPage() {
        const follow = 'next';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }

    /**
     * Follows Hateoas rel=first
     */
    firstPage() {
        const follow = 'first';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }

    /**
     * Follows Hateoas rel=last
     */
    lastPage() {
        const follow = 'last';
        let rel = this.hateoas.find(obj => {
            return follow === obj.rel
        });
        this.followRel(rel);
    }
}

window.customElements.define('tag-service-list', TagServiceList);
